zeppelin:
  image: apache/zeppelin:0.10.1
  resources:
    limits:
      memory: "4096Mi"
      cpu: "2000m"

replicas: 1

hadoop:
  useConfigMap: true
  configMapName: hadoop-hadoop
  configPath: /usr/hadoop-3.3.2/etc/hadoop

spark:
  driverMemory: 1g
  executorMemory: 1g
  numExecutors: 2

ingress:
  enabled: true
  annotations: 
    # kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/auth-secret: zeppelin-tls-secret
  path: /
  pathType: Prefix
  hosts:
    - zeppelin.10.10.33.102.nip.io
  tls: []
    # - secretName: zeppelin-tls-secret
    #   hosts: zeppelin.local

nodeSelector: {}
